# Generated by Django 3.1.6 on 2021-05-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210501_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-Posta Adresi'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ad Soyad'),
        ),
    ]
