# Generated by Django 3.1.6 on 2021-05-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210503_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi (GG/AA/YY)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/profile_pics/default.jpg', null=True, upload_to='profile_pics', verbose_name='Pofil Fotoğrafı Ekle'),
        ),
    ]
