# Generated by Django 3.1.6 on 2021-05-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210503_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.FileField(default='settings.MEDIA_ROOT/profile_pics/default.jpg', upload_to='profile_pics', verbose_name='Pofil Fotoğrafı Ekle'),
        ),
    ]
