# Generated by Django 3.1.6 on 2021-05-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210503_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.FileField(default='/profile_pics/default.jpg', upload_to='profile_pics', verbose_name='Pofil Fotoğrafı Ekle'),
        ),
    ]
